lines = [
    "name: CI\n",
    "\n",
    "on:\n",
    "  push:\n",
    "    branches: [main]\n",
    "  pull_request:\n",
    "    branches: [main]\n",
    "\n",
    "jobs:\n",
    "  backend-test:\n",
    "    name: Backend Tests\n",
    "    runs-on: ubuntu-latest\n",
    "    defaults:\n",
    "      run:\n",
    "        working-directory: ./backend\n",
    "    steps:\n",
    "      - name: Checkout code\n",
    "        uses: actions/checkout@v4\n",
    "\n",
    "      - name: Setup Node.js\n",
    "        uses: actions/setup-node@v4\n",
    "        with:\n",
    "          node-version: '20'\n",
    "          cache: 'npm'\n",
    "          cache-dependency-path: backend/package-lock.json\n",
    "\n",
    "      - name: Install dependencies\n",
    "        run: npm ci\n",
    "\n",
    "      - name: Run tests\n",
    "        run: npm test -- --coverage\n",
    "        env:\n",
    "          MONGODB_URI: ${{ secrets.MONGODB_URI }}\n",
    "          JWT_SECRET: test-secret-key\n",
    "          FRONTEND_URL: http://localhost:5173\n",
    "\n",
    "      - name: Upload coverage reports\n",
    "        uses: codecov/codecov-action@v4\n",
    "        if: success()\n",
    "        with:\n",
    "          files: ./backend/coverage/lcov.info\n",
    "          flags: backend\n",
    "\n",
    "  frontend-test:\n",
    "    name: Frontend Tests\n",
    "    runs-on: ubuntu-latest\n",
    "    defaults:\n",
    "      run:\n",
    "        working-directory: ./frontend\n",
    "    steps:\n",
    "      - name: Checkout code\n",
    "        uses: actions/checkout@v4\n",
    "\n",
    "      - name: Setup Node.js\n",
    "        uses: actions/setup-node@v4\n",
    "        with:\n",
    "          node-version: '20'\n",
    "          cache: 'npm'\n",
    "          cache-dependency-path: frontend/package-lock.json\n",
    "\n",
    "      - name: Install dependencies\n",
    "        run: npm ci\n",
    "\n",
    "      - name: Run tests\n",
    "        run: npm test -- --coverage\n",
    "\n",
    "      - name: Upload coverage reports\n",
    "        uses: codecov/codecov-action@v4\n",
    "        if: success()\n",
    "        with:\n",
    "          files: ./frontend/coverage/lcov.info\n",
    "          flags: frontend\n",
]

with open('.github/workflows/ci.yml', 'w', encoding='utf-8', newline='\n') as f:
    f.writelines(lines)

print('Clean YAML written!')