import mongoose from 'mongoose'

/**
 * DoubtSignal — Contextual Doubt-Anchored Polling
 *
 * Captures the exact moment a student loses the thread. Stored anonymously:
 * the `studentHash` is HMAC-SHA256(userId, roomSalt) — a teacher cannot reverse
 * it back to a user, but the same student is counted once per question if they
 * mark again later (aggregation treats them as one).
 *
 * Per-room `salt` lives on Room.doubtSalt; generated by the doubtService when
 * the first signal arrives, regenerated when the room ends (so signatures
 * don't carry over across sessions).
 */
const doubtSignalSchema = new mongoose.Schema({
  roomId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Room',
    required: true
  },
  studentHash: {
    type: String,
    required: true,
    match: /^[a-f0-9]{64}$/,
    index: true
  },
  segmentIndex: {
    type: Number,
    required: true,
    min: 0,
    index: true
  },
  // milliseconds offset within the segment where the student clicked
  transcriptOffsetMs: {
    type: Number,
    default: 0,
    min: 0
  },
  // Whether the student later retracted this signal within the retract window
  retracted: {
    type: Boolean,
    default: false
  },
  // NEW: Wall-clock timestamp when the client sent the signal.
  // Server may use this if it needs to derive recordingOffsetMs
  // (more accurate than relying on the client's guess).
  clientSentAt: {
    type: Date,
    default: Date.now
  },
  // NEW: Teacher's recording clock at the moment of the signal,
  // in milliseconds from roomStartedAt. This is what the teacher UI
  // displays as "lost at 02:34" — wall-clock time relative to recording start.
  // Stored explicitly because the teacher's latest position may shift
  // before the signal arrives at the server.
  recordingOffsetMs: {
    type: Number,
    default: null,
    min: 0
  },
  // NEW: Snapshot of the teacher's most-recently broadcast transcript text
  // at the moment of the signal. Stored on the signal itself so the spike
  // can render context even if the teacher's transcript has since advanced.
  // Empty string if no transcript was available.
  utteranceSnapshot: {
    type: String,
    default: ''
  },
  // Client-supplied context (optional): device type, etc. — kept generic to
  // avoid leaking identity info.
  client: {
    type: { type: String, default: 'unknown' }
  },
  createdAt: {
    type: Date,
    default: Date.now,
    index: true
  }
})

// Composite index: room + segment gives fast aggregation per-segment counts.
// Created with TTL removed; data is intentionally retained for analysis.
doubtSignalSchema.index({ roomId: 1, segmentIndex: 1 })
// One student can only have a single active signal per segment (duplicate taps are
// ignored at write time, not via a unique index so we can keep multiple historical
// signals if retraction toggling is enabled).

// Used by doubtful aggregation: count distinct students per segment.
doubtSignalSchema.statics.countDistinctStudentsBySegment = async function (roomId) {
  return this.aggregate([
    { $match: { roomId: new mongoose.Types.ObjectId(String(roomId)), retracted: false } },
    { $group: { _id: '$segmentIndex', uniqueStudents: { $addToSet: '$studentHash' } } },
    { $project: { segmentIndex: '$_id', count: { $size: '$uniqueStudents' }, _id: 0 } },
    { $sort: { segmentIndex: 1 } }
  ])
}

// NEW: count distinct students per recordingOffsetMs bucket.
// Useful for the teacher UI to show "students lost at recording time 02:34"
// without needing to know the segment index. Buckets are 1-second windows.
doubtSignalSchema.statics.countDistinctStudentsByRecordingTime = async function (roomId, bucketMs = 1000) {
  return this.aggregate([
    { $match: { roomId: new mongoose.Types.ObjectId(String(roomId)), retracted: false, recordingOffsetMs: { $ne: null } } },
    {
      $project: {
        bucket: {
          $multiply: [
            { $floor: { $divide: ['$recordingOffsetMs', bucketMs] } },
            bucketMs
          ]
        },
        // Carry forward fields we still need in later stages
        studentHash: 1,
        utteranceSnapshot: 1
      }
    },
    { $group: {
      _id: '$bucket',
      uniqueStudents: { $addToSet: '$studentHash' },
      sampleUtterance: { $first: '$utteranceSnapshot' }
    } },
    { $project: {
      recordingOffsetMs: '$_id',
      count: { $size: '$uniqueStudents' },
      sampleUtterance: '$sampleUtterance',
      _id: 0
    } },
    { $sort: { recordingOffsetMs: 1 } }
  ])
}

const DoubtSignal = mongoose.model('DoubtSignal', doubtSignalSchema)
export default DoubtSignal