apiVersion: v1
kind: ConfigMap
metadata:
  name: spandan-api-gateway-config
  namespace: spandan
data:
  GATEWAY_CORS_ORIGINS: "*"
  LOG_LEVEL: "INFO"
  REDIS_HOST: "spandan-redis"
  REDIS_PORT: "6379"
  AUTH_SERVICE_URL: "http://spandan-auth-service:8080"
  POLLING_SERVICE_URL: "http://spandan-polling-service:8081"
  ANALYTICS_SERVICE_URL: "http://spandan-analytics-service:8083"
  TRANSCRIPTION_SERVICE_URL: "http://spandan-transcription-service:8085"
  QGS_SERVICE_URL: "http://spandan-question-generation-service:8086"
  QRS_SERVICE_URL: "http://spandan-question-review-service:8087"
  NS_SERVICE_URL: "http://spandan-notification-service:8087"
  RS_SERVICE_URL: "http://spandan-recording-service:8088"
  RESPONSE_SERVICE_URL: "http://spandan-response-service:8084"
  RT_GATEWAY_WS_URL: "http://spandan-realtime-communication-service:8090"
