apiVersion: v1
kind: ServiceAccount
metadata:
  name: spandan-api-gateway
  namespace: spandan
  labels:
    app: spandan-api-gateway
    component: infrastructure
automountServiceAccountToken: false
