package com.spandan.notification.domain.enums;

public enum NotificationType {
    QUESTIONS_GENERATED,
    QUESTION_GENERATION_FAILED,
    REVIEW_COMPLETED,
    QUIZ_STARTING,
    QUIZ_COMPLETED,
    TEACHER_ANALYTICS_READY,
    STUDENT_ANALYTICS_READY,
    LEADERBOARD_GENERATED,
    SESSION_ANALYTICS_COMPLETED,
    TRANSCRIPT_GENERATION_FAILED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_REGISTERED,
    USER_PROFILE_UPDATED,
    USER_DEACTIVATED,
    LECTURE_CREATED,
    LECTURE_STARTED,
    LECTURE_ENDED,
    GRADING_COMPLETED,
    AUTO_GRADING_FAILED
}
