package com.spandan.notification.domain.enums;

public enum NotificationType {
    QUESTIONS_GENERATED,
    QUESTION_GENERATION_FAILED,
    REVIEW_COMPLETED,
    QUIZ_STARTING,
    TEACHER_ANALYTICS_READY,
    STUDENT_ANALYTICS_READY,
    LEADERBOARD_GENERATED,
    TRANSCRIPT_GENERATION_FAILED
}
