server {
    server_name spandan.fun www.spandan.fun;
    root /var/www/spandan.fun;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /dummy/ {
        alias /var/www/spandan.fun/dummy/;
        index index.html;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/spandan.fun/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/spandan.fun/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.spandan.fun) {
        return 301 https://$host$request_uri;
    }
    if ($host = spandan.fun) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name spandan.fun www.spandan.fun;
    return 404;
}